[package]
name = "perf_box"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ntokens"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }